client:
  _target_: src.clients.fedrecon_client.client_fn
  support_set_perc: 0.2
  joint_train_params: true
  n_public_layers: 2
  reconstruction_config:
    batch_size: 32
    lr: 0.001
    optimizer_name: adam
    gd_steps: 0
strategy:
  _target_: src.strategies.fedrecon.FedRecon
