class EnvironmentVariables:
    SERVER_ADDRESS = "COLEXT_SERVER_ADDRESS"
    DATA_HOME_FOLDER = "COLEXT_DATA_HOME_FOLDER"
    CLIENT_ID = "COLEXT_CLIENT_ID"
    DEVICE_TYPE = "COLEXT_DEVICE_TYPE"
    IBEX_SIMULATION = "IBEX_SIMULATION"
    LOG_TO_WANDB = "LOG_TO_WANDB"
    N_CLIENTS = "COLEXT_N_CLIENTS"
    COLEXT_JOB_ID = "COLEXT_JOB_ID"
