strategy:
  _target_: src.sl.sl_strategy.SlStrategy
  single_training_client: false
  common_server: false
  sl_configuration: plain
server_model:
  _target_: src.sl.sl_server_model.SlServerModel
client:
  _target_: src.sl.sl_client.SlClient
